export const formDataTitle = {
  FORM1_1: 'businessOperationalStatus',
  FORM1_2: 'businessPlanObj',
  FORM2_1: 'businessName',
  FORM2_2: 'businessType',
  FORM2_3: 'NEmployee',
  FORM2_4: 'productOrService',
  FORM2_5: 'salesChannel',
  FORM2_6: 'location',
  FORM3_1: 'customerDescription1',
  FORM3_2: 'customerIncome1',
  FORM3_3: 'customerDescription2',
  FORM3_4: 'customerIncome2',
  FORM3_5: 'customerDescription3',
  FORM3_6: 'customerIncome3',
  FORM4_1: 'productName1',
  FORM4_2: 'productDescription1',
  FORM4_3: 'productName2',
  FORM4_4: 'productDescription2',
  FORM4_5: 'productName3',
  FORM4_6: 'productDescription3',
  FORM4_7: 'productName4',
  FORM4_8: 'productDescription4',
  FORM4_9: 'productName5',
  FORM4_10: 'productDescription5',
  FORM5_1: 'successFactors1',
  FORM5_2: 'successFactors2',
  FORM5_3: 'successFactors3',
  FORM5_4: 'weakness1',
  FORM5_5: 'weakness2',
  FORM5_6: 'weakness3',
  FORM6_1: 'planCurrency',
  FORM6_2: 'initialInvestmentAmount',
  FORM6_3: 'investmentItem1',
  FORM6_4: 'investmentAmountItem1',
  FORM6_5: 'investmentItem2',
  FORM6_6: 'investmentAmountItem2',
  FORM6_7: 'investmentItem3',
  FORM6_8: 'investmentAmountItem3',
  FORM6_9: 'investmentItem4',
  FORM6_10: 'investmentAmountItem4',
  FORM6_11: 'investmentItem5',
  FORM6_12: 'investmentAmountItem5',
  FORM6_13: 'investmentItem6',
  FORM6_14: 'investmentAmountItem6',
  FORM6_15: 'investmentItem7',
  FORM6_16: 'investmentAmountItem7',
  FORM6_17: 'investmentItem8',
  FORM6_18: 'investmentAmountItem8',
  FORM6_19: 'investmentItem9',
  FORM6_20: 'investmentAmountItem9',
  FORM6_21: 'investmentItem10',
  FORM6_22: 'investmentAmountItem10',
  FORM6_23: 'planCurrencySymbol',
  FORM7_1: 'firstYearRevenue',
  FORM7_2: 'revenueGrowthRate',
  FORM7_3: 'COGSP',
  FORM7_4: 'wageCostP',
  FORM7_5: 'markCostP',
  FORM7_6: 'rentCostP',
  FORM7_7: 'genCostP',
  FORM7_8: 'depreCostP',
  FORM7_9: 'utilCostP',
  FORM7_10: 'otherCostP',
  FORM7_11: 'intCostP',
  FORM7_12: 'taxCostP',
  FORM7_13: 'planLanguage',
  REF_ID: 'refId',
};

export const radiosForm = {
  businessOperationalStatus: {
    'existing business': 'radio-1_1',
    'upcoming unlaunched business': 'radio-1_2',
  },
  businessPlanObj: {
    'To be used to request fund from investors': 'radio-2_1',
    'To be used to request fund from banks': 'radio-2_2',
    'For self-learning': 'radio-2_3',
    'To be used as reference for school/university project': 'radio-2_4',
    'To be used as reference for workplace projects': 'radio-2_5',
    'To be used to submit to a non-financial institution for approval (e.g. getting VISA approval, franchise approval, tenant approval)': 'radio-2_6',
    'Other reasons': 'radio-2_7',
  },
  productOrService: {
    'product': 'radio-1_1',
    'service': 'radio-1_2',
  },
  salesChannel: {
    'online': 'radio-2_1',
    'physical location': 'radio-2_2',
    'online and physical location': 'radio-2_3',
  },
  customerIncome1: {
    'low-income': 'radio1_1',
    'medium-income': 'radio1_2',
    'high-income': 'radio1_3',
  },
  customerIncome2: {
    'low-income': 'radio2_1',
    'medium-income': 'radio2_2',
    'high-income': 'radio2_3',
  },
  customerIncome3: {
    'low-income': 'radio3_1',
    'medium-income': 'radio3_2',
    'high-income': 'radio3_3',
  },
  planLanguage: {
    en: 'English (US)',
    de: 'German',
    fr: 'French',
    es: 'Spanish',
    it: 'Italian',
    'en-uk': 'English (UK)',
    nl: 'Dutch',
    ja: 'Japanese',
    ar: 'Arabic',
    sv: 'Swedish',
    fi: 'Finnish',
    no: 'Norwegian',
    da: 'Danish',
  }
}
