import { formDataTitle } from '../formTitle';

export const allSpecificQuestionsFormDataTitle = [
  formDataTitle.FORM_SPECIFIC_PRODUCT_QUESTION_1,
  formDataTitle.FORM_SPECIFIC_PRODUCT_QUESTION_2,
  formDataTitle.FORM_SPECIFIC_PRODUCT_QUESTION_3,
  formDataTitle.FORM_SPECIFIC_PRODUCT_QUESTION_4,
  formDataTitle.FORM_SPECIFIC_PRODUCT_QUESTION_5,
  formDataTitle.FORM_SPECIFIC_OPERATION_QUESTION_1,
  formDataTitle.FORM_SPECIFIC_OPERATION_QUESTION_2,
  formDataTitle.FORM_SPECIFIC_OPERATION_QUESTION_3,
  formDataTitle.FORM_SPECIFIC_OPERATION_QUESTION_4,
  formDataTitle.FORM_SPECIFIC_OPERATION_QUESTION_5,
];
