import { OpenAIChat } from '../../utils/OpenAIChat';

export const config = {
  runtime: 'edge',
  regions: ['iad1'],
};

const promptTemplates = {
  en: ({ businessType, productInfoPrompt }) =>
    ` Generate an outline for a business plan based on these details business description: ${businessType} ${productInfoPrompt} Generate insightful sub-topics only for these business plan topics: product, advertising, operation. Give answer in JSON format. Always include Pricing Strategy sub-topic in Product topic Don’t include anything about target market, customer group, marketing research, competitor analysis, or similar topics like that as it is already mentioned else where in the business plan. example of the desired output: { "product": [ "topic A", "topic B", "topic C", "topic D", "Pricing Strategy" ], "advertising": [ "topic A", "topic B", "topic C", "topic D", "topic E" ], "operation": [ "topic A", "topic B", "topic C", "topic D", "topic E" ] } change the topics A B C D E to relevant topics. Be mutually exclusive and collectively exhaustive when generating topics, You can generate more or less than 5 sub-topics for each topic depending on relevancy. Don't include the following topics or something similar into the new outline as they already exist: 1. Executive Summary 2. Market Analysis 2.1 industry overview 2.2 key market trends 2.3 SWOT 2.4 STP 2.4.1 Segmentation 2.4.2 Targeting 2.4.3 Positioning 3. Business objective 3.1 short-term 3.2 medium-term 3.3 long-term 4. Management 4.1 Employee Roster 5. Finance 5.1 Initial Investment 5.2 First Year Income Statement 5.3 Year 1 - 5 Income Statement 6. Risk and Mitigation`,
  de: ({ businessType, productInfoPrompt }) =>
    ` Generieren Sie eine Gliederung für einen Geschäftsplan basierend auf diesen Details Geschäftsbeschreibung: ${businessType} ${productInfoPrompt} Generieren Sie aussagekräftige Unterthemen nur für diese Geschäftsplanthemen: Produkt, Werbung, Betrieb. Geben Sie die Antwort im JSON-Format an. Fügen Sie immer das Unterthema "Preisstrategie" zum Thema "Produkt" hinzu. Enthalten Sie nichts über Zielmarkt, Kundengruppe, Marktforschung, Wettbewerbsanalyse oder ähnliche Themen, da diese bereits an anderer Stelle im Geschäftsplan erwähnt werden. Beispiel für das gewünschte Ergebnis: { "Produkt": [ "Thema A", "Thema B", "Thema C", "Thema D", "Preisstrategie" ], "Werbung": [ "Thema A", "Thema B", "Thema C", "Thema D", "Thema E", ], "Betrieb": [ "Thema A", "Thema B", "Thema C", "Thema D", "Thema E", ], } Ersetzen Sie die Themen A B C D E durch relevante Themen. Seien Sie bei der Generierung von Themen gegenseitig ausschließend und kollektiv erschöpfend. Sie können mehr oder weniger als 5 Unterthemen für jedes Thema generieren, abhängig von der Relevanz. Fügen Sie die folgenden Themen oder etwas Ähnliches nicht in die neue Gliederung ein, da sie bereits vorhanden sind: 1. Executive Summary 2. Marktanalyse 2.1 Branchenüberblick 2.2 Hauptmarkttrends 2.3 SWOT 2.4 STP 2.4.1 Segmentierung 2.4.2 Zielgruppenbestimmung 2.4.3 Positionierung 3. Geschäftsziel 3.1 Kurzfristig 3.2 Mittelfristig 3.3 Langfristig 4. Management 4.1 Mitarbeiterliste 5. Finanzen 5.1 Anfangsinvestition 5.2 Einnahmenübersicht für das erste Jahr 5.3 Einnahmenübersicht für Jahr 1 - 5 6. Risiko und Risikominderung`,
  fr: ({ businessType, productInfoPrompt }) =>
    ` Générez un plan détaillé pour un plan d'affaires basé sur ces détails Description de l'entreprise : ${businessType} ${productInfoPrompt} Générez des sous-thèmes pertinents uniquement pour les sujets suivants du plan d'affaires : produit, publicité, opération. Donnez la réponse au format JSON. Incluez toujours le sous-thème "Stratégie de tarification" dans le sujet "Produit". N'incluez rien sur le marché cible, le groupe de clients, la recherche marketing, l'analyse de la concurrence ou des sujets similaires, car ils sont déjà mentionnés ailleurs dans le plan d'affaires. Exemple du résultat souhaité : { "produit": [ "sujet A", "sujet B", "sujet C", "sujet D", "Stratégie de tarification" ], "publicité": [ "sujet A", "sujet B", "sujet C", "sujet D", "sujet E", ], "opération": [ "sujet A", "sujet B", "sujet C", "sujet D", "sujet E", ], } Remplacez les sujets A B C D E par des sujets pertinents. Soyez mutuellement exclusif et collectivement exhaustif lors de la génération des sujets. Vous pouvez générer plus ou moins de 5 sous-thèmes pour chaque sujet en fonction de leur pertinence. N'incluez pas les sujets suivants ou quelque chose de similaire dans le nouveau plan, car ils existent déjà : 1. Résumé exécutif 2. Analyse du marché 2.1 Aperçu de l'industrie 2.2 Tendances clés du marché 2.3 SWOT 2.4 STP 2.4.1 Segmentation 2.4.2 Ciblage 2.4.3 Positionnement 3. Objectif commercial 3.1 Court terme 3.2 Moyen terme 3.3 Long terme 4. Gestion 4.1 Liste des employés 5. Finances 5.1 Investissement initial 5.2 Compte de résultat de la première année 5.3 Compte de résultat de l'année 1 à 5 6. Risques et atténuation`,
  es: ({ businessType, productInfoPrompt }) =>
    ` Genera un esquema para un plan de negocios basado en estos detalles Descripción del negocio: ${businessType} ${productInfoPrompt} Genera subtemas relevantes solo para los temas del plan de negocios: producto, publicidad, operación. Proporciona la respuesta en formato JSON. Siempre incluye el subtema "Estrategia de precios" en el tema "Producto". No incluyas nada sobre el mercado objetivo, grupo de clientes, investigación de mercado, análisis de competidores o temas similares, ya que se mencionan en otras partes del plan de negocios. Ejemplo del resultado deseado: { "producto": [ "tema A", "tema B", "tema C", "tema D", "Estrategia de precios" ], "publicidad": [ "tema A", "tema B", "tema C", "tema D", "tema E", ], "operación": [ "tema A", "tema B", "tema C", "tema D", "tema E", ], } Reemplaza los temas A B C D E por temas relevantes. Sé mutuamente excluyente y colectivamente exhaustivo al generar los temas. Puedes generar más o menos de 5 subtemas para cada tema según su relevancia. No incluyas los siguientes temas o algo similar en el nuevo esquema, ya que ya existen: 1. Resumen ejecutivo 2. Análisis de mercado 2.1 Descripción de la industria 2.2 Tendencias clave del mercado 2.3 SWOT 2.4 STP 2.4.1 Segmentación 2.4.2 Segmentación 2.4.3 Posicionamiento 3. Objetivo empresarial 3.1 Corto plazo 3.2 Mediano plazo 3.3 Largo plazo 4. Gestión 4.1 Lista de empleados 5. Finanzas 5.1 Inversión inicial 5.2 Estado de resultados del primer año 5.3 Estado de resultados del año 1 al 5 6. Riesgo y mitigación`,
  it: ({ businessType, productInfoPrompt }) =>
    ` Genera una panoramica per un piano aziendale basata su questi dettagli Descrizione dell'azienda: ${businessType} ${productInfoPrompt} Genera sotto-argomenti significativi solo per questi argomenti del piano aziendale: prodotto, pubblicità, operazione. Fornisci la risposta nel formato JSON. Includi sempre il sotto-argomento "Strategia di prezzo" nell'argomento "Prodotto". Non includere nulla riguardo al mercato di riferimento, al gruppo di clienti, alla ricerca di mercato, all'analisi dei concorrenti o argomenti simili, poiché sono già menzionati altrove nel piano aziendale. Esempio dell'output desiderato: { "prodotto": [ "argomento A", "argomento B", "argomento C", "argomento D", "Strategia di prezzo" ], "pubblicità": [ "argomento A", "argomento B", "argomento C", "argomento D", "argomento E", ], "operazione": [ "argomento A", "argomento B", "argomento C", "argomento D", "argomento E", ], } Sostituisci gli argomenti A B C D E con argomenti pertinenti. Sii mutuamente esclusivo e collettivamente esaustivo durante la generazione degli argomenti. Puoi generare più o meno di 5 sotto-argomenti per ogni argomento a seconda della rilevanza. Non includere i seguenti argomenti o qualcosa di simile nell'outline nuovo poiché esistono già: 1. Riepilogo esecutivo 2. Analisi di mercato 2.1 Panoramica del settore 2.2 Principali tendenze di mercato 2.3 SWOT 2.4 STP 2.4.1 Segmentazione 2.4.2 Targeting 2.4.3 Posizionamento 3. Obiettivo aziendale 3.1 Breve termine 3.2 Medio termine 3.3 Lungo termine 4. Gestione 4.1 Elenco dipendenti 5. Finanza 5.1 Investimento iniziale 5.2 Conto economico del primo anno 5.3 Conto economico anno 1 - 5 6. Rischio e mitigazione`,
  nl: ({ businessType, productInfoPrompt }) =>
    ` Genereer een overzicht voor een bedrijfsplan op basis van deze gegevens Bedrijfsomschrijving: ${businessType} ${productInfoPrompt} Genereer inzichtelijke subonderwerpen alleen voor deze bedrijfsplanonderwerpen: product, reclame, operatie. Geef het antwoord in JSON-indeling. Voeg altijd het subonderwerp "Prijsstrategie" toe aan het onderwerp "Product". Vermeld niets over de doelmarkt, klantengroep, marktonderzoek, concurrentieanalyse of vergelijkbare onderwerpen, omdat deze al elders in het bedrijfsplan worden genoemd. Voorbeeld van de gewenste uitvoer: { "product": [ "onderwerp A", "onderwerp B", "onderwerp C", "onderwerp D", "Prijsstrategie" ], "reclame": [ "onderwerp A", "onderwerp B", "onderwerp C", "onderwerp D", "onderwerp E", ], "operatie": [ "onderwerp A", "onderwerp B", "onderwerp C", "onderwerp D", "onderwerp E", ], } Vervang de onderwerpen A B C D E door relevante onderwerpen. Wees onderling exclusief en collectief uitputtend bij het genereren van onderwerpen. U kunt meer of minder dan 5 subonderwerpen genereren voor elk onderwerp, afhankelijk van de relevantie. Voeg de volgende onderwerpen of iets soortgelijks niet toe aan het nieuwe overzicht, omdat deze al bestaan: 1. Executive Summary 2. Marktanalyse 2.1 Brancheschema 2.2 Belangrijkste markttrends 2.3 SWOT 2.4 STP 2.4.1 Segmentatie 2.4.2 Doelgroepbepaling 2.4.3 Positionering 3. Bedrijfsdoelstelling 3.1 Korte termijn 3.2 Middellange termijn 3.3 Lange termijn 4. Management 4.1 Lijst met werknemers 5. Financiën 5.1 Initiële investering 5.2 Resultatenrekening eerste jaar 5.3 Resultatenrekening jaar 1 - 5 6. Risico en beperking`,
  ja: ({ businessType, productInfoPrompt }) =>
    ` これらの詳細に基づいてビジネスプランの概要を生成します ビジネスの説明：${businessType} ${productInfoPrompt} ビジネスプランのトピック「製品」「広告」「オペレーション」に対してのみ洞察に富んだサブトピックを生成します。JSON形式で回答を提供してください。 製品のトピックには常に「価格戦略」のサブトピックを含めてください。 ターゲット市場、顧客グループ、マーケティングリサーチ、競合分析などについては、既にビジネスプランの他の場所で言及されているため、新しい概要に含めないでください。 期待される出力の例： { "製品": [ "トピックA", "トピックB", "トピックC", "トピックD", "価格戦略" ], "広告": [ "トピックA", "トピックB", "トピックC", "トピックD", "トピックE", ], "オペレーション": [ "トピックA", "トピックB", "トピックC", "トピックD", "トピックE", ], } トピックA、B、C、D、Eを関連するトピックに置き換えてください。 トピックを生成する際には、相互に排他的であり、総合的に網羅的であるようにしてください。 関連性に応じて、各トピックに5つ以上または5つ未満のサブトピックを生成することができます。 以下のトピックまたは類似のトピックを新しい概要に含めないでください。既に存在しています： 1. エグゼクティブサマリー 2. 市場分析 2.1 業界概要 2.2 主要な市場トレンド 2.3 SWOT 2.4 STP 2.4.1 セグメンテーション 2.4.2 ターゲティング 2.4.3 ポジショニング 3. ビジネス目標 3.1 短期 3.2 中期 3.3 長期 4. 管理 4.1 従業員リスト 5. 財務 5.1 初期投資 5.2 第1年の損益計算書 5.3 第1年から第5年までの損益計算書 6. リスクと緩和`,
  sv: ({ businessType, productInfoPrompt }) =>
    ` Generera en översikt för en affärsplan baserad på dessa detaljer Företagsbeskrivning: ${businessType} ${productInfoPrompt} Generera insiktsfulla underämnen endast för dessa affärsplanämnen: produkt, reklam, drift. Ge svaret i JSON-format. Inkludera alltid underämnet "Prissättningsstrategi" i ämnet "Produkt". Inkludera inte något om målmarknad, kundgrupp, marknadsundersökning, konkurrensanalys eller liknande ämnen, eftersom de redan nämns på annat håll i affärsplanen. Exempel på önskat resultat: { "produkt": [ "ämne A", "ämne B", "ämne C", "ämne D", "Prissättningsstrategi" ], "reklam": [ "ämne A", "ämne B", "ämne C", "ämne D", "ämne E", ], "drift": [ "ämne A", "ämne B", "ämne C", "ämne D", "ämne E", ], } Byt ut ämnena A B C D E mot relevanta ämnen. Var ömsesidigt exklusiv och kollektivt uttömmande vid generering av ämnen. Du kan generera fler eller färre än 5 underämnen för varje ämne beroende på relevans. Inkludera inte följande ämnen eller liknande i den nya översikten eftersom de redan finns: 1. Verksamhetsöversikt 2. Marknadsanalys 2.1 Branschöversikt 2.2 Viktiga marknadstrender 2.3 SWOT 2.4 STP 2.4.1 Segmentering 2.4.2 Målgruppsbestämning 2.4.3 Positionering 3. Affärsmål 3.1 Kort sikt 3.2 Medellång sikt 3.3 Lång sikt 4. Ledning 4.1 Anställningslista 5. Ekonomi 5.1 Initial investering 5.2 Resultaträkning för första året 5.3 Resultaträkning för år 1 - 5 6. Risk och åtgärder`,
  fi: ({ businessType, productInfoPrompt }) =>
    ` Luo liiketoimintasuunnitelman yhteenveto näiden tietojen perusteella Liiketoiminnan kuvaus: ${businessType} ${productInfoPrompt} Luo havainnollisia alaotsikoita vain näille liiketoimintasuunnitelman aiheille: tuote, mainonta, toiminta. Anna vastaus JSON-muodossa. Sisällytä aina hinnoittelustrategian alaotsikko tuoteaiheeseen. Älä sisällytä mitään kohdemarkkinoista, asiakasryhmästä, markkinatutkimuksesta, kilpailija-analyysistä tai vastaavista aiheista, koska ne on jo mainittu muualla liiketoimintasuunnitelmassa. Esimerkki halutusta tulosteesta: { "tuote": [ "aihe A", "aihe B", "aihe C", "aihe D", "Hinnoittelustrategia" ], "mainonta": [ "aihe A", "aihe B", "aihe C", "aihe D", "aihe E", ], "toiminta": [ "aihe A", "aihe B", "aihe C", "aihe D", "aihe E", ], } Vaihda aiheet A B C D E vastaaviin aiheisiin. Ole toisensa poissulkevia ja yhteisesti kattavia aiheita luodessasi. Voit luoda enemmän tai vähemmän kuin 5 alaotsikkoa kullekin aiheelle niiden merkityksen perusteella. Älä sisällytä seuraavia aiheita tai vastaavia uuteen yhteenvetoon, koska ne ovat jo olemassa: 1. Toimitusjohtajan yhteenveto 2. Markkina-analyysi 2.1 Toimialan yleiskatsaus 2.2 Tärkeimmät markkinatrendit 2.3 SWOT 2.4 STP 2.4.1 Segmentointi 2.4.2 Kohdistaminen 2.4.3 Asemointi 3. Liiketoiminnan tavoite 3.1 Lyhytaikainen 3.2 Keskipitkä aikaväli 3.3 Pitkäaikainen 4. Johtaminen 4.1 Työntekijäluettelo 5. Rahoitus 5.1 Alkuperäinen sijoitus 5.2 Ensimmäisen vuoden tuloslaskelma 5.3 Vuosi 1 - 5 tuloslaskelma 6. Riskit ja lieventäminen`,
  da: ({ businessType, productInfoPrompt }) =>
    ` Generer en oversigt over en forretningsplan baseret på disse detaljer Virksomhedsbeskrivelse: ${businessType} ${productInfoPrompt} Generer indsigtsfulde underemner kun for disse forretningsplanemner: produkt, reklame, drift. Giv svaret i JSON-format. Inkluder altid underemnet "Prisstrategi" i produkt-emnet. Undlad at inkludere noget om målmarked, kundegruppe, markedsundersøgelse, konkurrentanalyse eller lignende emner, da de allerede er nævnt andre steder i forretningsplanen. Eksempel på det ønskede output: { "produkt": [ "emne A", "emne B", "emne C", "emne D", "Prisstrategi" ], "reklame": [ "emne A", "emne B", "emne C", "emne D", "emne E", ], "drift": [ "emne A", "emne B", "emne C", "emne D", "emne E", ], } Skift emnerne A B C D E ud med relevante emner. Vær gensidigt eksklusiv og kollektivt udtømmende ved generering af emner. Du kan generere flere eller færre end 5 underemner for hvert emne afhængigt af relevans. Undlad at inkludere følgende emner eller noget lignende i den nye oversigt, da de allerede eksisterer: 1. Executive Summary 2. Markedsanalyse 2.1 Branchegennemgang 2.2 Vigtige markedsudviklinger 2.3 SWOT 2.4 STP 2.4.1 Segmentering 2.4.2 Målretning 2.4.3 Positionering 3. Forretningsmål 3.1 Kort sigt 3.2 Mellemlang sigt 3.3 Lang sigt 4. Ledelse 4.1 Medarbejderliste 5. Økonomi 5.1 Indledende investering 5.2 Resultatopgørelse for første år 5.3 Resultatopgørelse for år 1 - 5 6. Risiko og afbødning`,
  no: ({ businessType, productInfoPrompt }) =>
    ` Generer en oversikt over en forretningsplan basert på disse detaljene Bedriftsbeskrivelse: ${businessType} ${productInfoPrompt} Generer innsiktsfulle underemner bare for disse forretningsplanemnene: produkt, annonsering, drift. Gi svaret i JSON-format. Inkluder alltid underemnet "Prisstrategi" i produkt-emnet. Ikke inkluder noe om målmarked, kundegruppe, markedsundersøkelse, konkurrentanalyse eller lignende emner, da de allerede er nevnt andre steder i forretningsplanen. Eksempel på ønsket utdata: { "produkt": [ "emne A", "emne B", "emne C", "emne D", "Prisstrategi" ], "annonsering": [ "emne A", "emne B", "emne C", "emne D", "emne E", ], "drift": [ "emne A", "emne B", "emne C", "emne D", "emne E", ], } Bytt ut emnene A B C D E med relevante emner. Vær gjensidig eksklusiv og kollektivt uttømmende når du genererer emner. Du kan generere flere eller færre enn 5 underemner for hvert emne avhengig av relevans. Ikke inkluder følgende emner eller noe lignende i den nye oversikten, da de allerede eksisterer: 1. Executive Summary 2. Markedsanalyse 2.1 Bransjeoversikt 2.2 Viktige markedsutviklinger 2.3 SWOT 2.4 STP 2.4.1 Segmentering 2.4.2 Målretting 2.4.3 Plassering 3. Forretningsmål 3.1 Kortsiktig 3.2 Middelsiktig 3.3 Langsiktig 4. Ledelse 4.1 Ansatte 5. Økonomi 5.1 Innledende investering 5.2 Resultatregnskap for første år 5.3 Resultatregnskap for år 1 - 5 6. Risiko og avbøtende tiltak`,
};

export default async function POST(request: Request) {
  const { businessType, productInfoPrompt, planLanguage } =
    await request.json();

  const prompt = promptTemplates[planLanguage]({
    businessType,
    productInfoPrompt,
  });

  const payload = {
    model: 'gpt-4o-mini-2024-07-18',
    messages: [
      {
        role: 'user',
        content: `<|begin_of_text|><|start_header_id|>system<|end_header_id|> You are an insghtful business consultant who always gives output in purely JSON format. Do not include the beginning sentence or ending sentence in your output. Just include the JSON object.<|eot_id|><|start_header_id|>user<|end_header_id|> ${prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>`,
      },
    ],
    max_tokens: 1000,
    temperature: 0.5,
    presence_penalty: 1.15,
    frequency_penalty: 0.2,
  };
  return OpenAIChat(payload, 'json');
}
