import { useEffect, useState } from 'react';
import { formDataTitle } from '../constants/formTitle';

export const useLoadFormData = () => {
  const [formData, setFormData] = useState({});
  useEffect(() => {
    const result = JSON.parse(localStorage.getItem('formData')) || {};
    setFormData(result);
  }, []);

  return {
    businessPlanObj: formData[formDataTitle.FORM1_2]?.value || '',
    businessOperationalStatus: formData[formDataTitle.FORM1_1]?.value || '',
    planLanguage: formData[formDataTitle.FORM1_3]?.value || '',
    businessName: formData[formDataTitle.FORM2_1]?.value || '',
    businessType: formData[formDataTitle.FORM2_2]?.value || '',
    NEmployee: formData[formDataTitle.FORM2_3]?.value || '',
    productOrService: formData[formDataTitle.FORM2_4]?.value || '',
    salesChannel: formData[formDataTitle.FORM2_5]?.value || '',
    location: formData[formDataTitle.FORM2_6]?.value || '',
    customerDescription1: formData[formDataTitle.FORM3_1]?.value || '',
    customerIncome1: formData[formDataTitle.FORM3_2]?.value || '',
    customerDescription2: formData[formDataTitle.FORM3_3]?.value || '',
    customerIncome2: formData[formDataTitle.FORM3_4]?.value || '',
    customerDescription3: formData[formDataTitle.FORM3_5]?.value || '',
    customerIncome3: formData[formDataTitle.FORM3_6]?.value || '',
    productName1: formData[formDataTitle.FORM4_1]?.value || '',
    productName2: formData[formDataTitle.FORM4_3]?.value || '',
    productName3: formData[formDataTitle.FORM4_5]?.value || '',
    productName4: formData[formDataTitle.FORM4_7]?.value || '',
    productName5: formData[formDataTitle.FORM4_9]?.value || '',
    productDescription1: formData[formDataTitle.FORM4_2]?.value || '',
    productDescription2: formData[formDataTitle.FORM4_4]?.value || '',
    productDescription3: formData[formDataTitle.FORM4_6]?.value || '',
    productDescription4: formData[formDataTitle.FORM4_8]?.value || '',
    productDescription5: formData[formDataTitle.FORM4_10]?.value || '',
    successFactors1: formData[formDataTitle.FORM5_1]?.value || '',
    successFactors2: formData[formDataTitle.FORM5_2]?.value || '',
    successFactors3: formData[formDataTitle.FORM5_3]?.value || '',
    weakness1: formData[formDataTitle.FORM5_4]?.value || '',
    weakness2: formData[formDataTitle.FORM5_5]?.value || '',
    weakness3: formData[formDataTitle.FORM5_6]?.value || '',
    planCurrency: formData[formDataTitle.FORM6_1]?.value || '',
    initialInvestmentAmount: formData[formDataTitle.FORM6_2]?.value || 0,
    investmentItem1: formData[formDataTitle.FORM6_3]?.value || '',
    investmentAmountItem1: formData[formDataTitle.FORM6_4]?.value || 0,
    investmentItem2: formData[formDataTitle.FORM6_5]?.value || '',
    investmentAmountItem2: formData[formDataTitle.FORM6_6]?.value || 0,
    investmentItem3: formData[formDataTitle.FORM6_7]?.value || '',
    investmentAmountItem3: formData[formDataTitle.FORM6_8]?.value || 0,
    investmentItem4: formData[formDataTitle.FORM6_9]?.value || '',
    investmentAmountItem4: formData[formDataTitle.FORM6_10]?.value || 0,
    investmentItem5: formData[formDataTitle.FORM6_11]?.value || '',
    investmentAmountItem5: formData[formDataTitle.FORM6_12]?.value || 0,
    investmentItem6: formData[formDataTitle.FORM6_13]?.value || '',
    investmentAmountItem6: formData[formDataTitle.FORM6_14]?.value || 0,
    investmentItem7: formData[formDataTitle.FORM6_15]?.value || '',
    investmentAmountItem7: formData[formDataTitle.FORM6_16]?.value || 0,
    investmentItem8: formData[formDataTitle.FORM6_17]?.value || '',
    investmentAmountItem8: formData[formDataTitle.FORM6_18]?.value || 0,
    investmentItem9: formData[formDataTitle.FORM6_19]?.value || '',
    investmentAmountItem9: formData[formDataTitle.FORM6_20]?.value || 0,
    investmentItem10: formData[formDataTitle.FORM6_21]?.value || '',
    investmentAmountItem10: formData[formDataTitle.FORM6_22]?.value || 0,
    planCurrencySymbol: formData[formDataTitle.FORM6_23]?.value || '',
    firstYearRevenue: formData[formDataTitle.FORM7_1]?.value || 0,
    revenueGrowthRate: formData[formDataTitle.FORM7_2]?.value || 0,
    COGSP: formData[formDataTitle.FORM7_3]?.value || 0,
    wageCostP: formData[formDataTitle.FORM7_4]?.value || 0,
    markCostP: formData[formDataTitle.FORM7_5]?.value || 0,
    rentCostP: formData[formDataTitle.FORM7_6]?.value || 0,
    genCostP: formData[formDataTitle.FORM7_7]?.value || 0,
    depreCostP: formData[formDataTitle.FORM7_8]?.value || 0,
    utilCostP: formData[formDataTitle.FORM7_9]?.value || 0,
    otherCostP: formData[formDataTitle.FORM7_10]?.value || 0,
    intCostP: formData[formDataTitle.FORM7_11]?.value || 0,
    taxCostP: formData[formDataTitle.FORM7_12]?.value || 0,
    refId: formData[formDataTitle.REF_ID] || '',
    specificProductQuestion1: formData[formDataTitle.FORM_SPECIFIC_PRODUCT_QUESTION_1] || '',
    specificProductQuestion2: formData[formDataTitle.FORM_SPECIFIC_PRODUCT_QUESTION_2] || '',
    specificProductQuestion3: formData[formDataTitle.FORM_SPECIFIC_PRODUCT_QUESTION_3] || '',
    specificProductQuestion4: formData[formDataTitle.FORM_SPECIFIC_PRODUCT_QUESTION_4] || '',
    specificProductQuestion5: formData[formDataTitle.FORM_SPECIFIC_PRODUCT_QUESTION_5] || '',
    specificProductAnswer1: formData[formDataTitle.FORM_SPECIFIC_PRODUCT_ANSWER_1]?.value || '',
    specificProductAnswer2: formData[formDataTitle.FORM_SPECIFIC_PRODUCT_ANSWER_2]?.value || '',
    specificProductAnswer3: formData[formDataTitle.FORM_SPECIFIC_PRODUCT_ANSWER_3]?.value || '',
    specificProductAnswer4: formData[formDataTitle.FORM_SPECIFIC_PRODUCT_ANSWER_4]?.value || '',
    specificProductAnswer5: formData[formDataTitle.FORM_SPECIFIC_PRODUCT_ANSWER_5]?.value || '',
    specificOperationQuestion1: formData[formDataTitle.FORM_SPECIFIC_OPERATION_QUESTION_1] || '',
    specificOperationQuestion2: formData[formDataTitle.FORM_SPECIFIC_OPERATION_QUESTION_2] || '',
    specificOperationQuestion3: formData[formDataTitle.FORM_SPECIFIC_OPERATION_QUESTION_3] || '',
    specificOperationQuestion4: formData[formDataTitle.FORM_SPECIFIC_OPERATION_QUESTION_4] || '',
    specificOperationQuestion5: formData[formDataTitle.FORM_SPECIFIC_OPERATION_QUESTION_5] || '',
    specificOperationAnswer1: formData[formDataTitle.FORM_SPECIFIC_OPERATION_ANSWER_1]?.value || '',
    specificOperationAnswer2: formData[formDataTitle.FORM_SPECIFIC_OPERATION_ANSWER_2]?.value || '',
    specificOperationAnswer3: formData[formDataTitle.FORM_SPECIFIC_OPERATION_ANSWER_3]?.value || '',
    specificOperationAnswer4: formData[formDataTitle.FORM_SPECIFIC_OPERATION_ANSWER_4]?.value || '',
    specificOperationAnswer5: formData[formDataTitle.FORM_SPECIFIC_OPERATION_ANSWER_5]?.value || '',

  };
};
